name: PR Review

on:
  pull_request:
    branches: [ master ]

jobs:
  review:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint Pull Request
        uses: mr-linter/mr-linter-ga@v0.2.0
        env:
          MR_LINTER_HTTP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
